language: python
python:
    - "2.5"
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"

install: 
    - pip install six
    - pip install plumbum

before_script:
    - "cd tests"

script: nosetests -vv

notifications:
    email:
        on_success: change
        on_failure: change
